### ISSUE TITLE
First row full of barbarians

### ISSUE THREAD

**Issue by vishnu-1821** [bitsUnxte/bitsUnxte.github.io#7]
Barbarians seem to have united to form the vanguard 
![image](https://user-images.githubusercontent.com/95849020/146719730-3f486d98-d081-432c-9911-fc0adfebd122.png)

**Comment by vaibhavdevnani7** [comment]
😂😂fixed it in the morning, was getting 3 blank responses everytime from the database, thats why the barbarians😂
